Repository AlmostGreatBand/lemon-android, pull requests merged in 2021-06, with the labels that each got.

#31 17 transactions
  app/build.gradle
  app/src/main/java/com/agb/lemon_android/di/App.kt
  build.gradle
  core-ui/src/main/java/com/agb/core_ui/utils/utils.kt
  core-ui/src/main/res/values/colors.xml
  core/src/main/java/com/agb/core/common/Result.kt
  core/src/main/java/com/agb/core/common/exceptions/LemonException.kt
  core/src/main/java/com/agb/core/di/coreModule.kt
  core/src/main/java/com/agb/core/domain/model/Card.kt
  core/src/main/java/com/agb/core/domain/model/Transaction.kt
  data/src/main/java/com/agb/data/remote/AuthRemoteDataSource.kt
  data/src/main/java/com/agb/data/remote/HttpExceptionHandler.kt
  data/src/main/java/com/agb/data/remote/UserRemoteDataSource.kt
  data/src/main/java/com/agb/data/remote/api/AuthApi.kt
  data/src/main/java/com/agb/data/remote/api/UserApi.kt
  feature-cards/.gitignore
  feature-cards/build.gradle
  feature-cards/consumer-rules.pro
  feature-cards/proguard-rules.pro
  feature-cards/src/main/AndroidManifest.xml
  feature-cards/src/main/java/com/agb/feature_cards/core/datasource/CardsDataSource.kt
  feature-cards/src/main/java/com/agb/feature_cards/core/domain/models/Card.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/models/CardsResponse.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/remote/CardsApi.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/remote/CardsRemoteDataSource.kt
  feature-cards/src/main/java/com/agb/feature_cards/di/cardsModule.kt
  feature-home/build.gradle
  feature-home/src/main/java/com/agb/feature_home/di/HomeModule.kt
  feature-home/src/main/java/com/agb/feature_home/ui/HomeFragment.kt
  feature-home/src/main/java/com/agb/feature_home/ui/HomeViewModel.kt
  feature-home/src/main/java/com/agb/feature_home/ui/cards/CardsAdapter.kt
  feature-home/src/main/java/com/agb/feature_home/ui/cards/CardsDiffUtils.kt
  feature-home/src/main/java/com/agb/feature_home/ui/cards/CardsItemDecorator.kt
  feature-home/src/main/java/com/agb/feature_home/ui/transactions/StickyHeaderTransactionsDecorator.kt
  feature-home/src/main/java/com/agb/feature_home/ui/transactions/TransactionRecyclerItem.kt
  feature-home/src/main/java/com/agb/feature_home/ui/transactions/TransactionsAdapter.kt
  feature-home/src/main/java/com/agb/feature_home/ui/transactions/TransactionsDiffUtils.kt
  feature-home/src/main/java/com/agb/feature_home/ui/transactions/TransactionsPageAdapter.kt
  feature-home/src/main/res/layout/fragment_home.xml
  feature-home/src/main/res/layout/item_card.xml
  feature-home/src/main/res/layout/item_date.xml
  feature-home/src/main/res/layout/item_transaction.xml
  feature-home/src/main/res/layout/item_transaction_page.xml
  feature-transactions/.gitignore
  feature-transactions/build.gradle
  feature-transactions/consumer-rules.pro
  feature-transactions/proguard-rules.pro
  feature-transactions/src/main/AndroidManifest.xml
  feature-transactions/src/main/java/com/agb/feature_transactions/core/datasource/TransactionsDataSource.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/core/domain/models/Transaction.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/models/TransactionsResponse.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/remote/TransactionsApi.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/remote/TransactionsRemoteDataSource.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/di/transactionsModule.kt
  settings.gradle
Labels: api, core, feature, ui/ux

#25 Create LICENSE
  LICENSE
Labels: documentation

#32 feat: add card caching support
  core/src/main/java/com/agb/core/common/Result.kt
  feature-cards/build.gradle
  feature-cards/src/main/java/com/agb/feature_cards/core/datasource/CardsDataSource.kt
  feature-cards/src/main/java/com/agb/feature_cards/core/domain/repository/CardsRepository.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/local/CardsLocalDataSource.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/local/db/CardsDao.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/local/db/CardsDatabase.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/local/db/CardsEntity.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/remote/CardsApi.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/remote/CardsRemoteDataSource.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/remote/CardsResponse.kt
  feature-cards/src/main/java/com/agb/feature_cards/di/cardsModule.kt
  feature-home/src/main/java/com/agb/feature_home/ui/HomeViewModel.kt
  feature-home/src/main/java/com/agb/feature_home/ui/transactions/TransactionsPageAdapter.kt
  feature-transactions/build.gradle
Labels: db

#33 feat: implement caching for transactions
  CHANGELOG.md
  build.gradle
  feature-cards/src/main/java/com/agb/feature_cards/core/domain/repository/CardsRepository.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/local/CardsLocalDataSource.kt
  feature-cards/src/main/java/com/agb/feature_cards/data/local/db/CardsDao.kt
  feature-home/src/main/java/com/agb/feature_home/di/HomeModule.kt
  feature-home/src/main/java/com/agb/feature_home/ui/HomeViewModel.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/core/datasource/TransactionsDataSource.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/core/domain/repository/TransactionsRepository.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/local/TransactionsLocalDataSource.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/local/db/TransactionConverters.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/local/db/TransactionsDao.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/local/db/TransactionsDatabase.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/local/db/TransactionsEntity.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/data/remote/TransactionsRemoteDataSource.kt
  feature-transactions/src/main/java/com/agb/feature_transactions/di/transactionsModule.kt
Labels: db
